### ISSUE TITLE
Curious how amazon_fresh_delivery_slot_chrome.py works?

### ISSUE THREAD

**Issue by StarWindMoonCloud** [pcomputo/Whole-Foods-Delivery-Slot#10]
I have successfully found delivery slot twice using this script.
Ironically I didn't "SLOTS OPEN!", didn't hear any sound, I believe the code is not executed at all. However, it can lock the slot when available. I didn't see there's any related logic from the script. How did you achieve it??

**Comment by wuzandfuzz** [comment]
Hi @StarWindMoonCloud quick question - is it searching for all slots? I.E. today, monday, tues, weds.
