### ISSUE TITLE
amazon_fresh... throws exception

### ISSUE THREAD

**Issue by tglauner** [pcomputo/Whole-Foods-Delivery-Slot#17]
Great scripts and truly helpful! Thank you. I successfully ran whole_foods_delivery_slot_chrome and it works like a charm. So, I do not think it's my environment. 

Issue is with amazon_fresh_delivery_slot_chrome which I executed and see via a print statement that an exception is always thrown.

I am in Windows 10 Enterprise, V10.0.16299 and Chrome Version 80.0.3987.162 (Official Build) (64-bit)

This is from powershell:
prompt> python .\amazon_fresh_delivery_slot_chrome.py

DevTools listening on ws://127.0.0.1:49373/devtools/browser/7a3a703d-71d5-419a-b325-b9e78c886afd
.\amazon_fresh_delivery_slot_chrome.py:18: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 18 of the file .\amazon_fresh_delivery_slot_chrome.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  soup = bs4.BeautifulSoup(html)
refreshed
.\amazon_fresh_delivery_slot_chrome.py:26: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 26 of the file .\amazon_fresh_delivery_slot_chrome.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  soup = bs4.BeautifulSoup(html)
In Exception
refreshed
In Exception
refreshed
In Exception

and then it just proceeds like this. I added the print('In Expcetion') statement.

**Comment by pcomputo** [comment]
hey thank you for using the script! I added your suggestion to the script! thank you.

**Comment by tglauner** [comment]
the point wasn't really my addition but that it throws an exception and the
script does not work. Can you please test on your side.

Tim
