### ISSUE TITLE
amazon_fresh_delivery_slot_chrome.py doesn't notify on windows 10 + chrome

### ISSUE THREAD

**Issue by wangzizhao** [pcomputo/Whole-Foods-Delivery-Slot#19]
Thanks for the great script!

When I use amazon_fresh_delivery_slot_chrome.py on windows 10 + chrome, I notice there is an open slot but the script doesn't recognize it but keep refreshing the page.

I wonder how I should change the [line 30](https://github.com/pcomputo/Whole-Foods-Delivery-Slot/blob/master/amazon_fresh_delivery_slot_chrome.py#L30) to make it work.

Thanks!

**Comment by pcomputo** [comment]
Thanks for reaching out.
I'd have to see a screenshot of the page. I will have to dig deeper into that HTML to know what caused it to not trigger.

**Comment by wangzizhao** [comment]
Thanks!

I didn't take the screenshot but rushed to place the order this time. I will try to see if I can reproduce it and get a screenshot next time.

**Comment by pcomputo** [comment]
No worries, thanks for letting me know.
Did you happen to check if there was "SLOTS OOPEN!" on the terminal? I'm trying to figure out if the audio didn't work.

**Comment by wangzizhao** [comment]
No, I didn't see "SLOTS OPEN". The audio works well for me in the Whole Foods scripts, so I guess it should also work for fresh.

**Comment by shern15** [comment]
For what its worth, when I used the amazon script on Windows 10 + Chrome, even when it found open slots for me it never printed out "Open Slots!" for me either.

The page kept refreshing even when Open Slots were found, and it kept skipping the try block and going into the "AttributeError" except block.

And obviously I did not hear any sound, even though I imported the winsound module.

**Comment by pcomputo** [comment]
So Amazon Fresh got rid of the div that was there before for time slots. I captured the new one the new one, and am testing it now.

This can become one endless GAN between Amazon and me. :P

**Comment by Sir-Branch** [comment]
Hi, same problem! Didn't notify but the terminal printed:

**Comment by pcomputo** [comment]
pushed changes

**Comment by bricep** [comment]
> 
> 
> Hi, similar problem! Didn't notify but the terminal printed:
> 
> refreshed
> refreshed
> ....
> refreshed
> SLOTS OPEN!
> 'say' is not recognized as an internal or external command, operable program or batch file.
> 
> **Running on Windows 10**
> I'm guessing in my case it's something to do with the sound library.

I incorporated my own fix for this as I encountered this on Windows. My fix was to use the win32com.client. My code is:

from win32com.client import Dispatch
speak = Dispatch("SAPI.SpVoice")
speak.Speak("[whatever you want to say]")

**Comment by pcomputo** [comment]
There is already a solution to Windows verbal notifications in the Readme.
