### ISSUE TITLE
Can't install requirements.txt on Windows machine

### ISSUE THREAD

**Issue by Ch0senByFate** [pcomputo/Whole-Foods-Delivery-Slot#2]
Trying to run this on windows, ran into the following issues:
1. Could not find a version that satisfies the requirement bonjour==0.3
 -  resolved this by removing the line altogether
2. Could not find a version that satisfies the requirement numpy==1.8.0rc1
 -  resolved by using pip to install a different numpy version and changing .txt file to match
3. ObjC runtime not found - "You're not running on MacOS X, and don't use GNUstep. I don't know how to build PyObjC on such a platform."
 - Don't know how to resolve this

Note that I've never previously installed python before trying this repo, so maybe I'm doing some dumb stuff

**Comment by ava1ar** [comment]
Yes, this is workable only on Mac as-is. Having same issues on Linux.

**Comment by Ch0senByFate** [comment]
You Mac people are taking all my grocery slots!

**Comment by pcomputo** [comment]
Can you try it with the updated requirements.txt?

You basically just need these packages for the script to run:

```
beautifulsoup4==4.8.2
chromedriver-binary==81.0.4044.69.0
selenium==3.141.0
urllib3==1.25.8
webdriver-manager==2.3.0
```
Thanks a lot for trying the script out and helping.

**Comment by ava1ar** [comment]
Works fine for me now! Thanks!

**Comment by Ch0senByFate** [comment]
Yep, works. Issue resolved. Thanks!

**Comment by Ch0senByFate** [comment]
Got a slot thanks to this! You're a lifesaver.

**Comment by ava1ar** [comment]
I am using it for Amazon Fresh deliveries with slight modifications and also able to get slot after 3 days trying manually.
