### ISSUE TITLE
Noob Guide 

### ISSUE THREAD

**Issue by 2dangerous** [pcomputo/Whole-Foods-Delivery-Slot#21]
Hi All, this looks to be a great tool, however, i've never used Python, so any other programming language. Is there a Noob version of this where it would say:
1. Install Python 3 (select C:/ folder to install, etc.)
2. Install Chrome Driver 
3. Run Python.exe (i don't know if this the right way to run)
Etc. 

Or any good videos I can view to learn some basics and incorporate this script. 
Sorry, i know this is not an issue, however, I wasn't sure how to add comments here. 
Thanks again.

**Comment by pcomputo** [comment]
You can install Python  2.7 for Windows: `https://datascience.com.co/how-to-install-python-2-7-and-3-6-in-windows-10-add-python-path-281e7eae62a`
Once you do that and have cloned the repository: `git clone <repo-name>`
You can run the script of choice by `python <script-name>.py` from the terminal

**Comment by pcomputo** [comment]
https://www.notion.so/using-pcomputo-s-script-to-find-whole-foods-delivery-slots-acbb6d71ef934da7b6822b1df451a11c
