### ISSUE TITLE
Visual notification?

### ISSUE THREAD

**Issue by avekifes** [pcomputo/Whole-Foods-Delivery-Slot#24]
Would it be possible to include an option that changes the audio notification to a visual one? I have Chrome refreshing automatically while minimized to the taskbar in Windows 10 - ideally, I'd want the tab to simply flash in the taskbar when a delivery slot opens up.

(I do a lot of audio recording throughout the day, so an audio notification might interfere with my work or not play at all due to exclusivity such as ASIO.)

**Comment by pcomputo** [comment]
You can remove the say commands and instead try:

from plyer import notification

```
notification.notify(
    title='Here is the title',
    message='Here is the message',
    app_name='Here is the application name',
    app_icon='path/to/the/icon.png'
)
```
I haven't tested it. https://stackoverflow.com/questions/15921203/how-to-create-a-system-tray-popup-message-with-python-windows

**Comment by tangerinehuge** [comment]
I updated the Chrome autobuy script to open a popup window when it finds a slot. It works on windows 10 now as well as Mac.

**Comment by pcomputo** [comment]
@ tangerinehuge  added a fix to his branch, I pressed on the wrong button, ugh.
