### ISSUE TITLE
Windows Error

### ISSUE THREAD

**Issue by acrete** [pcomputo/Whole-Foods-Delivery-Slot#25]
I'm not sure this is an error but my terminal is reading the below. I am on Windows. My Chrome browser launches and otherwise seems to be working (It did not alert me of any time slots opening while I was testing).

λ python whole_foods_delivery_windows.py

DevTools listening on ws://127.0.0.1:51805/devtools/browser/37a6ace0-96cd-438d-8df3-80451acd016c
[8024:7836:0408/224426.450:ERROR:browser_switcher_service.cc(238)] XXX Init()
Traceback (most recent call last):
  File "whole_foods_delivery_windows.py", line 50, in <module>
    getWFSlot('https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1')
  File "whole_foods_delivery_windows.py", line 14, in getWFSlot
    html = driver.page_sourced
AttributeError: 'WebDriver' object has no attribute 'page_sourced'

**Comment by pcomputo** [comment]
I think you need to give the whole executable path to the Chrome driver, something like:

`driver = webdriver.Chrome(executable_path=r"C:\Chrome\chromedriver.exe")`

**Comment by acrete** [comment]
Still having same issue after change the path. Got it working on whole_foods_delivery_slot_chrome. What is the best solution for audio alert on windows using the above? import winsound?

**Comment by pcomputo** [comment]
yep, you'll find more instructions in Readme. If you don't like that one, you can check out what other packages are out there for Windows. I've used winsound, so know about it.
