### ISSUE TITLE
Amazon Fresh Slot notification

### ISSUE THREAD

**Issue by corgnation** [pcomputo/Whole-Foods-Delivery-Slot#27]
Amazon Fresh script will give the notification that slots are open after the first refresh, but there are none available.

**Comment by pcomputo** [comment]
you were probably on not screen 5 in Readme when the script started refreshing.

**Comment by shern15** [comment]
On Windows 10 + Chrome I experienced the same thing this morning using the latest commit and can confirm that I was indeed on screen 5.

**Comment by williford** [comment]
Amazon must have modified the page template, the element reference here https://github.com/pcomputo/Whole-Foods-Delivery-Slot/blob/master/amazon_fresh_delivery_slot_chrome.py#L32
does not exist on the schedule page (using Windows 10 + chrome).

What I did was change the xpath to:
/html/body/div[5]/div[1]/div/div[2]/div/div/div/div/div[1]/div[4]/div[2]/div/div[3]/div/div/div/h4
you can find this via the chrome debugger, inspect element, copy full xpath.
I also had to change the searched text to:
"No delivery windows available."

This is pretty fragile though and will break whenever Amazon updates the page.

**Comment by wuzandfuzz** [comment]
Agreed, I had to make a similar change.  It's ok tho it's not like they are exposing anything useful I can see from the page

**Comment by DougF5000** [comment]
I just submitted this item which I think may be similar, if not identical, to what @williford and @wuzandfuzz were discussion: https://github.com/pcomputo/Whole-Foods-Delivery-Slot/issues/52.
