### ISSUE TITLE
WF delivery autobuy throwing error - Windows/Chrome

### ISSUE THREAD

**Issue by jkbenzene** [pcomputo/Whole-Foods-Delivery-Slot#33]
Having an issue with autobuy script on Windows with chrome for WF delivery.  Attached is the traceback report (it wasn't pasting well).

Any thoughts?

[WF delivery traceback.txt](https://github.com/pcomputo/Whole-Foods-Delivery-Slot/files/4462821/WF.delivery.traceback.txt)

**Comment by pcomputo** [comment]
you can increase the sleep time before the line that throws error to 8 or 10 or something. The page never loaded within the time thats specified in the script and hence the button was not found.

**Comment by jkbenzene** [comment]
Thanks! I will give it a try. Pages are probably loading slow due to number of users trying to currently access the system.
