### ISSUE TITLE
Suggested change to account for multiple h4s

### ISSUE THREAD

**Issue by jtravisnorton** [pcomputo/Whole-Foods-Delivery-Slot#37]
https://github.com/pcomputo/Whole-Foods-Delivery-Slot/blob/e0ecdb3e1472e9f489a37c7d1b6620c0cf338540/whole_foods_delivery_windows.py#L31

Suggest rewriting as follows to account for multiple h4s:
`next_slot_text = str([x.text for x in soup.findAll('h4', class_ ='ufss-slotgroup-heading-text a-text-normal')])`

**Comment by pcomputo** [comment]
Awesome, thank you!

**Comment by pcomputo** [comment]
pushed changes. Thanks a lot! :)
