### ISSUE TITLE
I'm stucked at "step 3: use virtual environment ". Please help me out 😭

### ISSUE THREAD

**Issue by Scarlettlol** [pcomputo/Whole-Foods-Delivery-Slot#38]
While I typed in terminal: "virtualenv -p /usr/bin/python2.7 --distribute temp-python"
The terminal shows below:
"virtualenv: error: unrecognized arguments: --distribute"

But! I've successfully installed virtualenv and python...

Please help me with this problem. (By the way, I'm a beginner at learning to code😂)
Thank you so much!

**Comment by pcomputo** [comment]
if you have installed Python, you should try to run any file with the commands in the Readme of this repository. Let's say you wanted to run the file: whole_foods_delivery_autobuy_windows.py
you'd go to terminal and type: `python whole_foods_delivery_autobuy_windows.py`
Your terminal should be pointing to this repository, else it won't find the file.

**Comment by small3687** [comment]
I am completely lost as to what to do. Is virtualenv another thing I have to download? I have tried double clicking the python script and it flashes a command window but then does nothing else. Do you mind breaking it down into even smaller steps please? I gave it about 5 hours of work yesterday and still couldn't manage to figure out what I need to do.

**Comment by efjacobson** [comment]
@small3687 i got this working on both a macos and a windows machine and did not have to do that step. dont double click it like its a regular windows program. you have to navigate to the folder where the scripts are (eg `whole_foods_delivery_autobuy_windows.py`), execute it with python (eg `python .\whole_foods_delivery_windows.py`) and then you will be good to go.

when i say "navigate to the folder where the scripts are" i mean go there with the command line. if you are using windows i recommend powershell. once you are there if you enter `ls` you should see the scripts, like so:

![Annotation 2020-04-11 122332](https://user-images.githubusercontent.com/6315388/79053067-50219600-7bef-11ea-9e5a-550ff8666fbe.png)

on both machines it was not able to initially find the chromedriver, so i made changes like this answer suggests https://stackoverflow.com/a/58158456

what that means is that i opened the `whole_foods_delivery_windows.py` file in a text editor and changed it. it originally looked like this:

```
import bs4

from selenium import webdriver

import sys
import time

import winsound


def getWFSlot(productUrl):
   driver = webdriver.Chrome()
   ...rest of the code
```

but now it looks like this:

```
import bs4

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

import sys
import time

import winsound


def getWFSlot(productUrl):
   driver = webdriver.Chrome(ChromeDriverManager().install())
   ...rest of the code
```

best of luck

**Comment by Scarlettlol** [comment]
I installed the app "Anaconda-Navigator". And finally, it works! Haha
