### ISSUE TITLE
macOS Mojave os.system()

### ISSUE THREAD

**Issue by StarWindMoonCloud** [pcomputo/Whole-Foods-Delivery-Slot#4]
It's great, I got a slot. But didn't hear any sound notification as claimed
" this automated script can notify you (yes notifies you verbally, so you can go about your tasks)"

**Comment by StarWindMoonCloud** [comment]
let me know if you may need any env details

**Comment by aaronkw** [comment]
Looks like the audio notification only works on MacOS

**Comment by pcomputo** [comment]
The sound works on Linux and Mac. For windows you need to:

```
import winsound
duration = 1000  # milliseconds
freq = 440  # Hz
winsound.Beep(freq, duration)
```

**Comment by StarWindMoonCloud** [comment]
O, mine is mac actually.
macOS Mojave
Version 10.14.2

**Comment by pcomputo** [comment]
Looks like Mojave doesn't support os.system() sounds. You can try:

```
import sys
sys.stdout.write('\a')
sys.stdout.flush()
```

comment out the `os.system()` lines in the script.

If the above command doesn't work then try running:

`$ sudo apt-get install python-pygame`
`from pygame import mixer
mixer.init() 
alert=mixer.Sound('bell.wav')
alert.play()`
