### ISSUE TITLE
Chrome window closes after alerting

### ISSUE THREAD

**Issue by spathan27** [pcomputo/Whole-Foods-Delivery-Slot#47]
My process ran fine, i got the alert notification however before i click anything the chrome windwow got closed by itself.
here is what it displayed on the screen when i got the notification

----
refreshed
SLOTS OPEN 3!

Process finished with exit code 0`

**Comment by pcomputo** [comment]
are you running it through PyCharm?

**Comment by spathan27** [comment]
> are you running it through PyCharm?

Yes. Any thing I need to do at my end if I’m using pycharm?

**Comment by pcomputo** [comment]
Is it possible for you to run the script from the terminal? not through some IDE?

**Comment by spathan27** [comment]
I’ll do it. Thanks for responding.
