### ISSUE TITLE
Please Help and Thank you for sharing this

### ISSUE THREAD

**Issue by mp42244** [pcomputo/Whole-Foods-Delivery-Slot#5]
on my linux mint machine I consistently get the following error message " Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rrTU6M/chromedriver-binary/"

I am sure its something i am not doing right but need to get this working to avoid a trip to the grocery store for i have an underlining condition that makes it very unattractive.

**Comment by pcomputo** [comment]
Hello! I am here to help you. Thank you for using the script.

Can you please tell me the command that is throwing that error? I can help you with the step by step installation.

**Comment by mp42244** [comment]
Hello Pooja,

Thank you so much for responding . I get that error message when I try to install requirements.txt by using:

pip install -r requirements.txt

**Comment by pcomputo** [comment]
ah. Which Python version are you using? `python --version`

**Comment by mp42244** [comment]
Python 2.7.15rc1

**Comment by pcomputo** [comment]
Instead or running the requirements.txt can you try to manually run these commands and see if you still get the error? 

`sudo apt-get install python-bs4
sudo apt-get install python-pip
sudo pip install selenium
sudo pip install urllib3
`

**Comment by mp42244** [comment]
sure

**Comment by mp42244** [comment]
i get   the following error message when i run the first command

File "<stdin>", line 1
    sudo apt-get install python-bs4
           ^
SyntaxError: invalid syntax
>>>

**Comment by mp42244** [comment]
apologies i tried running from wrong directory. will correct

**Comment by mp42244** [comment]
here are results

matt@matt-ideacentre-300S-08IHH:~$ sudo apt-get install python-bs4
[sudo] password for matt: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libgtkglext1 libtinyxml2.6.2v5
Use 'sudo apt autoremove' to remove them.
Recommended packages:
  python-chardet python-lxml | python-html5lib
The following NEW packages will be installed:
  python-bs4
0 upgraded, 1 newly installed, 0 to remove and 784 not upgraded.
Need to get 67.9 kB of archives.
After this operation, 375 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 python-bs4 all 4.6.0-1 [67.9 kB]
Fetched 67.9 kB in 0s (161 kB/s)    
Selecting previously unselected package python-bs4.
(Reading database ... 257625 files and directories currently installed.)
Preparing to unpack .../python-bs4_4.6.0-1_all.deb ...
Unpacking python-bs4 (4.6.0-1) ...
Setting up python-bs4 (4.6.0-1) ...
matt@matt-ideacentre-300S-08IHH:~$ sudo apt-get install python-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.1).
The following packages were automatically installed and are no longer required:
  libgtkglext1 libtinyxml2.6.2v5
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 784 not upgraded.
matt@matt-ideacentre-300S-08IHH:~$ sudo pip install selenium
The directory '/home/matt/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/matt/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting selenium
  Downloading https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl (904kB)
    100% |████████████████████████████████| 911kB 1.5MB/s 
Collecting urllib3 (from selenium)
  Downloading https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl (125kB)
    100% |████████████████████████████████| 133kB 6.3MB/s 
Installing collected packages: urllib3, selenium
Successfully installed selenium-3.141.0 urllib3-1.25.8
matt@matt-ideacentre-300S-08IHH:~$ sudo pip install urllib3
The directory '/home/matt/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/matt/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: urllib3 in /usr/local/lib/python2.7/dist-packages

**Comment by pcomputo** [comment]
Its confusing, it installed looks like. Can you try running the script and tell me what errors you get so we can start by installing those packages.

**Comment by mp42244** [comment]
Will do

**Comment by mp42244** [comment]
seems like im getting closer. i ran the script and got :+1: 

File "whole_foods_delivery_slot_chrome.py", line 50, in <module>
    getWFSlot('https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1')
  File "whole_foods_delivery_slot_chrome.py", line 15, in getWFSlot
    driver = webdriver.Chrome()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by pcomputo** [comment]
cool, so now you'd need the Chromedriver and run the script. Can you please run the following commands:

`sudo apt-get install unzip`
`wget -N http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip -P ~/Downloads`
`unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads`
making it an executable and moving it to /usr/local/share
`chmod +x ~/Downloads/chromedriver`
`sudo mv -f ~/Downloads/chromedriver /usr/local/share/chromedriver`
`sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver`
`sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver`

then try running the script. If it doesnt run with the above commands, then run the first three commands only. 
Then do to Downloads, copy paste the path to the chromedriver unzipped file. 
And then go back to the Python script and paste the copied path between the "()" in `driver = webdriver.Chrome()`

**Comment by mp42244** [comment]
getting closer. when i run the script i get the following error. looks like
i am on the wrong verison of chrome. i am on 75 not 80. thinking i should
upgrade?

matt@matt-ideacentre-300S-08IHH:~/Downloads/script/Whole-Foods-Delivery-Slot-master$
python whole_foods_delivery_slot_chrome.py
Traceback (most recent call last):
  File "whole_foods_delivery_slot_chrome.py", line 50, in <module>
    getWFSlot('
https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html?hasWorkingJavascript=1
')
  File "whole_foods_delivery_slot_chrome.py", line 15, in getWFSlot
    driver = webdriver.Chrome()
  File
"/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py",
line 81, in __init__
    desired_capabilities=desired_capabilities)
  File
"/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py",
line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File
"/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py",
line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File
"/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py",
line 321, in execute
    self.error_handler.check_response(response)
  File
"/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py",
line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not
created: This version of ChromeDriver only supports Chrome version 80

**Comment by pcomputo** [comment]
yep, you should try updating your Chrome

**Comment by mp42244** [comment]
I did and the script runs. Thanks so much !!!!

**Comment by mp42244** [comment]
Is there a new script I should be running which checks the next day too?

**Comment by pcomputo** [comment]
you'll keep running the same script. 
Also, keep running `git pull`. This will keep pulling any new changes I keep pushing.

**Comment by mp42244** [comment]
Been running latest script for 3 hours and no luck. Is that normal ?

**Comment by pcomputo** [comment]
yes, it depends when Amazon opens their slots. You can also keep checking the terminal, you'll keep seeing a bunch of "refresh" which indicates the script is working.

**Comment by mp42244** [comment]
Yes it’s definitely working! It’s really nicely done
