### ISSUE TITLE
False positives with Amazon Fresh script

### ISSUE THREAD

**Issue by DougF5000** [pcomputo/Whole-Foods-Delivery-Slot#52]
With a few tweaks to the notification code (using winsound instead of say), I managed to get the Amazon Fresh code running without apparent issue on windows. It ran fine for several hours and then shortly after midnight earlier today, it notified me that a slot had opened when in fact the output on the screen appeared identical to the way it had prior (which indicated there were no slots). I carefully checked text on screen to see if it matched the "no_open_slots" text and it appeared identical.

I then adding some instrumentation (additional print statements) to see which of the three branches were being triggered and was able to reproduce it. It appeared to be the first branch (the else: section under the first try:). 

I checked the xpath for the text on the page and it was nearly identical (only a single digit was different) and tried it again with the revised xpath. It ran for a while and then triggered the false positive again. 

Is this a known issue? If not, is there any information I can gather to help debug this? 

Thanks!

**Comment by pcomputo** [comment]
thank you for pointing it out. I'll look into this.

**Comment by DougF5000** [comment]
In case it's helpful, I've attached the output from the shell and the slightly tweaked code I was using. 
[amazon_fresh_delivery_slot_chrome_windows.zip](https://github.com/pcomputo/Whole-Foods-Delivery-Slot/files/4518604/amazon_fresh_delivery_slot_chrome_windows.zip)

**Comment by marcfischer123467** [comment]
lol I had to do the same thing on mac using chrome

**Comment by pcomputo** [comment]
awesome! thank you! :D I'll look at it! :)
