### ISSUE TITLE
Wont check out

### ISSUE THREAD

**Issue by acr79** [pcomputo/Whole-Foods-Delivery-Slot#53]
I've been trying to get the project to checke out and its not quite working.  It detects slots, selects the slot but when its on payment method it stops and says 

found a slot but it got taken, run script again

it never checks out though, could it be that its because its asking for payment selection instead of a single default payment?

**Comment by pcomputo** [comment]
is there a card for payment selected? 
The "found a slot but it got taken, run script again" happens if the script tried to click on the checkout button but Amazon redirected it to "no slots page". That happens if the slot got taken away. 
Is the checkout waiting for any input from your end or everything is selected?

**Comment by acr79** [comment]
Default card is selected for payment, I removed other cards just in case and same result.  I watched it live and it just sits at select payment and doesnt click through to the next page.  I can check out manually from there though.

**Comment by lllinusss** [comment]
> Default card is selected for payment, I removed other cards just in case and same result. I watched it live and it just sits at select payment and doesnt click through to the next page. I can check out manually from there though.

I can confirm this behavior.

**Comment by pcomputo** [comment]
it doesn't click immediately. There is a wait. How long did you wait for it? 
Also, its good to have a default card, otherwise the checkout wont succeed without payment.

**Comment by acr79** [comment]
It basically stops when it goes to the payment page I watched it for 5 minutes and looked on the terminal window and it says to rerun the script.  It seems to hit the payment page, then stop right there and goes to slot is gone.  Glad to send you a video of it

**Comment by pcomputo** [comment]
ah! I'm testing it now, I think Amazon may have changed a few things. Thanks a lot for bringing this to my attention, will let you know once changes are up.

**Comment by acr79** [comment]
Awesome thanks!  I was wondering if I was doing something wrong.  Appreciate the quick response and thanks for making this.

**Comment by pcomputo** [comment]
pushed the latest changes. You can git pull to get them.

**Comment by acr79** [comment]
testing stand by

**Comment by acr79** [comment]
worked! thanks for pushing that fix
