### ISSUE TITLE
Invalid If statement - no_slot_pattern == soup.find('h4', class_ ='a-alert-heading').text

### ISSUE THREAD

**Issue by amohap2** [pcomputo/Whole-Foods-Delivery-Slot#56]
If I print soup.find('h4', class_ ='a-alert-heading').text, the resulting text is :
Due to increased demand, available windows are limited. Please check back later or shop a
                Whole Foods Market
                    near you.

it is not:
'No delivery windows available. New windows are released throughout the day.'
   I believe both messages are h4, class='a-alert-heading',. The if statement will never be true.

**Comment by pcomputo** [comment]
I got rid of the whole h4. It seems very dynamic. This'll help make the script faster too.
