### ISSUE TITLE
Can't update driver path for autobuy. Can't find Firefox line in script as described in readme.

### ISSUE THREAD

**Issue by ignamiranda** [pcomputo/Whole-Foods-Delivery-Slot#59]
The readme says to look for `python driver = webdriver.Firefox(executable_path="<your-webdriver-path>")` in whole_foods_delivery_autobuy_windows.py but I can't find the line. I tried editing `driver = webdriver.Chrome()` to be `driver = webdriver.Firefox(executable_path="c/my/path/")` but that didn't work

**Comment by pcomputo** [comment]
can you try removing "executable_path" and trying it out?
