### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by bontchev** [pcomputo/Whole-Foods-Delivery-Slot#60]
I've read the hit job on you that was published in Vice by some moron who fancies himself a journalist but is really a SJW in disguise with an agenda and I wanted to tell you this:

Thank you for what you have done. Don't listen to the haters. There is nothing wrong with using one's programming skills in order to provide food for one's family in time of need. Your work is doubly to be commended for offering the result of it as open source, so that others who might not have the skills to make such a bot themselves could use yours or learn from it.

Don't pay attention to the idiotic claims that you are "creating a digital divide". I guess the same kind of people were opposed to the Internet (after all, not everybody has Internet connection, so not everybody can shop on-line) and even to the cars before that (which put at a "disadvantage" those who don't have a car and can't use it to shop for food).

I personally have to take care of my 84-year old mother, including buying food for both of us during the pandemic. We don't even have Amazon Fresh or Whole Foods in our country, so I can't use your bot directly - but I'll certainly study how it works and how it can be adapted so it can be used for the company here that offers on-line buying of groceries.

Once more, thank you for what you have done.

**Comment by pcomputo** [comment]
Thank you so much for your kind words! 
Please do let me know if I can help you in anyway! :D
