### ISSUE TITLE
Autobuy failed at last step

### ISSUE THREAD

**Issue by jhomsy2** [pcomputo/Whole-Foods-Delivery-Slot#63]
Hi. 
Using a Mac, and ran the latest commit for 
whole_foods_delivery_autobuy.py
(3d289a8f13aadd2f9f29e042dcddc4adee4f1187)

It worked well, except when it got to the end, it did not perform the final click for "place order." I had to do it manually (manual click worked, and order was placed).

This is what was shown on the screen as the script was running:

```
refreshed
SLOTS OPEN! 2
Clicked open slot
Selected slot and continued to next page
Payment method selected
Found a slot but it got taken, run script again. 2
```

Note that I added the "2" after "Found a slot but it got taken, run script again." on line 79 so I could tell where the script stopped.

**Comment by pcomputo** [comment]
Ah! Thank you for writing down the issue so well! It worked for me a while back. Did it work for you after this try?

**Comment by jhomsy2** [comment]
Hi. This happened on 4/27 using the latest code. I haven't tried it since (maybe I'll order again this week or next).
I noticed that you commented out lines 59, 67 and 71 in favor of lines 60, 66, and 72, respectively. I wonder if that has something to do with it, or whether this issue I had was a fluke. I'll let you know what happens when I try running it again.
