### ISSUE TITLE
Chrome Driver Crashes After "slots for delivery opened"

### ISSUE THREAD

**Issue by Frydafly** [pcomputo/Whole-Foods-Delivery-Slot#64]
I ran this program successfully about 14 days ago (I think) and it worked well & I got my delivery. 

Trying with the same code now and after the "slots for delivery opened" voice speaks, and I see "3 spots" in my terminal, the chrome driver crashes, reopens, and refreshes to the amazon page.

**Comment by pcomputo** [comment]
can you try pulling the latest code? `git pull` I tend to change the code as and how there are new changes to WholeFoods website.

**Comment by Frydafly** [comment]
Done! It works!
