### ISSUE TITLE
Force search for same-day

### ISSUE THREAD

**Issue by mzguy** [pcomputo/Whole-Foods-Delivery-Slot#65]
Amazon often offers delivery next day if the current day is unavailable. Any idea how to modify the script to ignore the next day, and respond only if same-day slots are available?

**Comment by pcomputo** [comment]
Probably, Line 23 in `wholefoods_delivery_autobuy.py` you could modify the slot_button as

```
if driver.find_element_by_xpath("//*[@id="shipoption-select"]/div/div/div/div/div[1]/div[2]/div[2]/div/ul/li[1]/span/span/span/button/div/div[1]").text == "Today": 
    #code from repo
else:
    #run script from start
```

**Comment by mzguy** [comment]
I'll try this sometime. Thanks!

**Comment by mzguy** [comment]
I'm getting "Invalid syntax" with the above substitution. I'm not good with Python. Is there an error somewhere in what you posted?

Also, is "#code from repo" something native to Python or did you intend I substitute something there?

Thanks!

**Comment by mzguy** [comment]
> 
> 
> I'm getting "Invalid syntax" with the above substitution. I'm not good with Python. Is there an error somewhere in what you posted?
> 
> Also, is "#code from repo" something native to Python or did you intend I substitute something there?
> 
> Thanks!

@pcomputo 
Could you please clarify?
