### ISSUE TITLE
NoneType' object has no attribute 'text

### ISSUE THREAD

**Issue by lari98** [pcomputo/Whole-Foods-Delivery-Slot#66]
from selenium import webdriver
from bs4 import BeautifulSoup
import pandas as pd
driver = webdriver.Chrome("D:/chromedriver")
products=[] #List to store name of the product
prices=[] #List to store price of the product
Descriptions=[] #List to store rating of the product
driver.get("https://www.nike.com/w/womens-lifestyle-shoes-13jrmz5e1x6zy7ok")
content = driver.page_source
soup = BeautifulSoup(content)
for a in soup.find_all('a',href=True, attrs={'class':'product-card__link-overlay'}):
    name = a.find('div', attrs={'class':'product-card__title'})
    price=a.find('div', attrs={'class':'product-card__price'})
    products.append(name.text)
    prices.append(price.text)
    Descriptions=a.find('li', attrs={'class':'product-card__subtitle'}) 
    #ratings.append(rating.text) 
df = pd.DataFrame({'Product Name':products,'Price':prices, 'Description' :Descriptions}) 
#,'Rating':ratings
df.to_csv('scraping .csv', index=False, encoding='utf-8')

Error products.append(name.text) AttributeError: 'NoneType' object has no attribute 'text'

_Originally posted by @lari98 in https://github.com/pcomputo/Whole-Foods-Delivery-Slot/issues/40#issuecomment-739682420_

**Comment by pcomputo** [comment]
sorry, this does not look like this repository's code
