### ISSUE TITLE
Issue after finding the slot

### ISSUE THREAD

**Issue by makrandp** [pcomputo/Whole-Foods-Delivery-Slot#7]
Hey, 
when i found the slot. i went to the payment page and after selecting the payment method. It took me back to the Schedule your order page and the slot was no longer available. Please investigate. 
Thanks!

**Comment by pcomputo** [comment]
That's because someone else checked out with that slot, so its no longer available through Amazon. 
The script worked correctly that it found an open slot and notified you. You can try running the script again to get a new slot.
